version: 2
jobs:
  build-and-test:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build the docker image
          command: docker build --tag=typo3-debian-ssh .
      - run:
          name: Run the docker web container
          background: true
          command: |
            docker run --env="SSH_USER=" --name=ssh typo3-debian-ssh
      - run:
          name: Check if the ssh is working
          command: |
            sleep 2; docker run --rm --link ssh alpine /bin/sh -c 'nc -zv ssh 22'

workflows:
  version: 2
  all:
    jobs:
      - build-and-test
