version: 2
jobs:
  build-and-test:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build the docker image
          command: docker build --tag=typo3-debian-ssh .
      # - run:
      #     name: Run the docker web container
      #     background: true
      #     command: |
      #       docker run --name=ssh typo3-debian-ssh
      # - run:
      #     name: Check if the ssh is working
      #     command: |
      #       docker run --rm alpine --link ssh /bin/sh -c ''

workflows:
  version: 2
  all:
    jobs:
      - build-and-test
